#!/bin/bash
echo "running custom build hook"

if [ -z "$CACHE_TAG" ]; then
  CACHE_TAG=latest
fi

case $CACHE_TAG in
  15-*)
    BUILD_WILDFLY_VERSION=15.0.1.Final
    ;;
  10-*)
    BUILD_WILDFLY_VERSION=10.1.0.Final
    ;;
  [1-9][0-9]-*)
    v=$(echo $CACHE_TAG | cut -f1 -d'-')
    BUILD_WILDFLY_VERSION=${v}.0.0.Final
    ;;
  *)
    BUILD_WILDFLY_VERSION=16.0.0.Final
    ;;
esac

JRE_VERSION=${BUILD_JRE_VERSION:-"8-jre-alpine"}
S6_VERSION=${BUILD_S6_VERSION:-v1.21.4.0}
WILDFLY_VERSION=${BUILD_WILDFLY_VERSION:-"15.0.0.Final"}
DOCKERFILE_PATH=${DOCKERFILE_PATH:-Dockerfile}
IMAGE_NAME=${IMAGE_NAME:-"soulwing/wildfly:$CACHE_TAG"}

echo "JRE_VERSION=${JRE_VERSION}"
echo "S6_VERSION=${S6_VERSION}"
echo "WILDFLY_VERSION=${WILDFLY_VERSION}"
echo "DOCKERFILE_PATH=${DOCKERFILE_PATH}"

docker build \
    --no-cache \
    --build-arg JRE_VERSION="$JRE_VERSION" \
    --build-arg WILDFLY_VERSION="$WILDFLY_VERSION" \
    --build-arg S6_VERSION="$S6_VERSION" \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
